name: Build Flutter APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Flutter installieren
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Aktuelle Version einsetzen

    - name: Abhängigkeiten installieren
      run: flutter pub get

    - name: APK erstellen
      run: flutter build apk --release

    - name: APK hochladen
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
