name: Build Flutter APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Flutter installieren
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Ersetze mit der aktuellen Version

    - name: Abhängigkeiten aktualisieren
          run: flutter pub upgrade
          
    - name: Abhängigkeiten installieren
      run: flutter pub get

    - name: APK erstellen
      run: flutter build apk --release

    - name: APK hochladen
      uses: actions/upload-artifact@v4  # **Hier von v3 auf v4 geändert**
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Flutter Clean & Pub Get
      run: flutter clean && flutter pub get

